repos:
  - repo: local
    hooks:
      - id: ng-lint
        name: ng-lint
        files: \.ts$
        stages: [pre-commit]
        language: system
        pass_filenames: false
        entry: ng lint
